# General Jekyll Config
pygments: true
url: http://renkun.me
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
safe: true

# Theme customization
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: renkun-ken
    #bitbucket:
    #hacker_news:
    stackexchange: 3473007
    stackoverflow: 2906900
    twitter: renkun_ken
    facebook: renkun.ken
    #tumblr:
    linkedin: kun-ren/30/275/760
    #gplus: 111105804545243552282

  # Personal information
  name: Kun Ren
  email: renkun@outlook.com
  tagline: "an enthusiast for data science"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-47159422-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true

  # MathJax support
  mathjax: true

  # Disqus support
  disqus: renkun-ken