# General Jekyll Config
url: http://renkun.me
exclude: [LICENSE, CNAME, README.md, .gitignore]
safe: true
lsi: false
#pygments: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Theme customization
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: renkun-ken
    stackexchange: 3473007
    stackoverflow: 2906900
    twitter: renkun_ken
    facebook: renkun.ken
    linkedin: kun-ren/30/275/760
    #gplus: 111105804545243552282
  author:
    gplus: "+KunRen"
  # Personal information
  name: Kun Ren
  email: renkun@outlook.com
  tagline: "an enthusiast for data science"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-47159422-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true

  # MathJax support
  mathjax: true

  # Disqus site-id
  disqus: renkun-ken

  # highlight.js theme
  # false to disable
  highlightjs: vs